"""
Office Document, Presentation, and Standalone App Generator for Antigravity Cloud Bridge.
Supports .docx, .pptx, .xlsx, .pdf, and standalone interactive .html web apps.
"""

import os
import sys
from datetime import datetime

def create_docx(title, sections, output_path=None, base_dir="./inbox"):
    import docx
    from docx.shared import Inches, Pt, RGBColor

    if not output_path:
        os.makedirs(base_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() else "_" for c in title)[:30]
        output_path = os.path.join(base_dir, f"{safe_title}_{timestamp}.docx")

    doc = docx.Document()
    
    # Title
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(title)
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.name = "Calibri"
    title_run.font.color.rgb = RGBColor(15, 23, 42)
    title_p.paragraph_format.space_after = Pt(10)

    # Subtitle / Metadata
    meta_p = doc.add_paragraph()
    meta_run = meta_p.add_run(f"Generated by Antigravity Cloud Bridge | {datetime.now().strftime('%d %B %Y')}")
    meta_run.font.size = Pt(10)
    meta_run.font.italic = True
    meta_run.font.color.rgb = RGBColor(100, 116, 139)
    meta_p.paragraph_format.space_after = Pt(16)

    # Sections
    for sec in sections:
        h = sec.get("heading")
        if h:
            h_p = doc.add_paragraph()
            h_run = h_p.add_run(h)
            h_run.font.size = Pt(13)
            h_run.font.bold = True
            h_run.font.name = "Calibri"
            h_run.font.color.rgb = RGBColor(30, 41, 59)
            h_p.paragraph_format.space_before = Pt(12)
            h_p.paragraph_format.space_after = Pt(6)

        c = sec.get("content")
        if isinstance(c, list):
            for item in c:
                p = doc.add_paragraph(style='List Bullet')
                p_run = p.add_run(str(item))
                p_run.font.size = Pt(11)
                p.paragraph_format.space_after = Pt(4)
        elif isinstance(c, str):
            for para in c.split("\n\n"):
                if para.strip():
                    p = doc.add_paragraph()
                    p_run = p.add_run(para.strip())
                    p_run.font.size = Pt(11)
                    p.paragraph_format.space_after = Pt(6)

    doc.save(output_path)
    return output_path

def create_pptx(title, subtitle, slides_data, output_path=None, base_dir="./inbox"):
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    if not output_path:
        os.makedirs(base_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() else "_" for c in title)[:30]
        output_path = os.path.join(base_dir, f"{safe_title}_{timestamp}.pptx")

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank_layout = prs.slide_layouts[6]

    # Title Slide
    title_slide = prs.slides.add_slide(blank_layout)
    txBox = title_slide.shapes.add_textbox(Inches(1.0), Inches(2.2), Inches(11.3), Inches(2.0))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(38)
    p.font.bold = True
    p.font.color.rgb = RGBColor(15, 23, 42)

    p2 = tf.add_paragraph()
    p2.text = subtitle or f"Antigravity Intelligence | {datetime.now().strftime('%B %Y')}"
    p2.font.size = Pt(18)
    p2.font.color.rgb = RGBColor(100, 116, 139)
    p2.space_before = Pt(14)

    # Content Slides
    for s_info in slides_data:
        slide = prs.slides.add_slide(blank_layout)
        h_box = slide.shapes.add_textbox(Inches(1.0), Inches(0.8), Inches(11.3), Inches(1.0))
        h_tf = h_box.text_frame
        h_tf.word_wrap = True
        h_p = h_tf.paragraphs[0]
        h_p.text = s_info.get("title", "")
        h_p.font.size = Pt(26)
        h_p.font.bold = True
        h_p.font.color.rgb = RGBColor(15, 23, 42)

        b_box = slide.shapes.add_textbox(Inches(1.0), Inches(2.0), Inches(11.3), Inches(4.8))
        b_tf = b_box.text_frame
        b_tf.word_wrap = True

        bullets = s_info.get("bullets", [])
        for i, b_text in enumerate(bullets):
            p = b_tf.paragraphs[0] if i == 0 else b_tf.add_paragraph()
            p.text = f"•  {b_text}"
            p.font.size = Pt(17)
            p.font.color.rgb = RGBColor(51, 65, 85)
            p.space_before = Pt(10)

    prs.save(output_path)
    return output_path

def create_xlsx(title, headers, rows, output_path=None, base_dir="./inbox"):
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment
    from openpyxl.utils import get_column_letter

    if not output_path:
        os.makedirs(base_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() else "_" for c in title)[:30]
        output_path = os.path.join(base_dir, f"{safe_title}_{timestamp}.xlsx")

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = title[:30] if title else "Sheet1"

    header_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")

    ws.append(headers)
    for col_num in range(1, len(headers) + 1):
        cell = ws.cell(row=1, column=col_num)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    for r in rows:
        ws.append(r)

    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            val_str = str(cell.value or "")
            if len(val_str) > max_len:
                max_len = len(val_str)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

    wb.save(output_path)
    return output_path

def create_pdf(title, sections, output_path=None, base_dir="./inbox"):
    import pymupdf

    if not output_path:
        os.makedirs(base_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() else "_" for c in title)[:30]
        output_path = os.path.join(base_dir, f"{safe_title}_{timestamp}.pdf")

    html_parts = [
        "<style>",
        "body { font-family: sans-serif; color: #1e293b; margin: 0; }",
        "h1 { color: #0f172a; font-size: 20px; border-bottom: 2px solid #3b82f6; padding-bottom: 6px; margin-bottom: 4px; }",
        ".meta { font-size: 9px; color: #64748b; font-style: italic; margin-bottom: 14px; }",
        "h2 { color: #1e40af; font-size: 13px; margin-top: 12px; margin-bottom: 6px; }",
        "p { font-size: 10.5px; line-height: 1.45; margin-bottom: 8px; color: #334155; }",
        "ul { margin-top: 4px; margin-bottom: 8px; padding-left: 18px; }",
        "li { font-size: 10.5px; line-height: 1.4; margin-bottom: 4px; color: #334155; }",
        "</style>",
        f"<h1>{title}</h1>",
        f"<div class='meta'>Generated by Antigravity Cloud Bridge | {datetime.now().strftime('%d %B %Y')}</div>"
    ]

    for sec in sections:
        h = sec.get("heading")
        if h:
            html_parts.append(f"<h2>{h}</h2>")
        c = sec.get("content")
        if isinstance(c, list):
            html_parts.append("<ul>")
            for it in c:
                html_parts.append(f"<li>{it}</li>")
            html_parts.append("</ul>")
        elif isinstance(c, str):
            for para in c.split("\n\n"):
                if para.strip():
                    html_parts.append(f"<p>{para.strip()}</p>")

    doc = pymupdf.open()
    page = doc.new_page(width=595, height=842)
    rect = pymupdf.Rect(40, 40, 555, 802)
    page.insert_htmlbox(rect, "".join(html_parts))
    doc.save(output_path, garbage=4, deflate=True)
    doc.close()
    return output_path

def create_standalone_app(title, app_code, output_path=None, base_dir="./inbox"):
    if not output_path:
        os.makedirs(base_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() else "_" for c in title)[:30]
        output_path = os.path.join(base_dir, f"{safe_title}_{timestamp}.html")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(app_code)

    return output_path
